export const FETCH_USER = 'FETCH_USER';
export const LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_USER = 'REGISTER_USER';

export const IS_USER_LOGGED_IN = "IS USER LOGGED IN";

export const INFO_UPDATE_REQUEST = "UPDATE REQUEST";

export const OPEN_MODAL = "OPEN MODAL";
export const OPEN_EXPERIENCE_MODAL = "OPEN EXPERIENCE MODAL";
export const SUBMIT_FROM_MODAL = "SUBMIT FROM MODAL";

export const CHANGE_PROFILE_PICTURE = "CHANGE PROFILE PICTURE";
export const CHANGE_CV = "CHANGE CV";