export const ADD_DRIVER = 'ADD_DRIVER';
export const ADD_DRIVER_SUCCESS = 'ADD_DRIVER_SUCCESS';

export const GET_DRIVERS = 'GET_DRIVERS';
export const GET_DRIVERS_SUCCESS = 'GET_DRIVERS_SUCCESS';

export const UPDATE_DRIVER = 'UPDATE_DRIVER';
export const UPDATE_DRIVER_SUCCESS = 'UPDATE_DRIVER_SUCCESS';

export const GET_DRIVER = 'GET_DRIVER';
export const GET_DRIVER_SUCCESS = 'GET_DRIVER_SUCCESS';

export const DELETE_DRIVER = 'DELETE_DRIVER';
export const DELETE_DRIVER_SUCCESS = 'DELETE_DRIVER_SUCCESS';

export const SELECT_DRIVER = 'SELECT_DRIVER';

export const AUTH_COMPANY = 'AUTH_COMPANY';
export const AUTH_COMPANY_SUCCESS = 'AUTH_COMPANY_SUCCESS';
export const AUTH_COMPANY_FAIL = 'AUTH_COMPANY_FAIL';

export const GET_COMPANY = 'GET_COMPANY';
export const GET_COMPANY_SUCCESS = 'GET_COMPANY_SUCCESS';

export const REGISTER_COMPANY = 'REGISTER_COMPANY';
export const REGISTER_COMPANY_SUCCESS = 'REGISTER_COMPANY_SUCCESS';

export const UPDATE_COMPANY = 'UPDATE_COMPANY';
export const UPDATE_COMPANY_SUCCESS = 'UPDATE_COMPANY_SUCCESS';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const FILTER_USERS = 'FILTER_USERS';
export const FILTER_USERS_SUCCESS = 'FILTER_USERS_SUCCESS';
export const FILTER_USERS_EMPTY = 'FILTER_USERS_EMPTY';

export const GET_CHART = 'GET_CHART';
export const GET_CHART_SUCCESS = 'GET_CHART_SUCCESS';

export const GET_CHART_CV = 'GET_CHART_CV';
export const GET_CHART_CV_SUCCESS = 'GET_CHART_CV_SUCCESS';

export const GET_CHART_TOP10 = 'GET_CHART_TOP10';
export const GET_CHART_TOP10_SUCCESS = 'GET_CHART_TOP10_SUCCESS';

export const GET_CHART_TOTAL_USERS = 'GET_CHART_TOTAL_USERS';
export const GET_CHART_TOTAL_USERS_SUCCESS = 'GET_CHART_TOTAL_USERS_SUCCESS';

export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';

